### ISSUE TITLE
Please export the focus function

### ISSUE THREAD

**Issue by SpadarShut** [romgain/react-select-event#10]
I've spent a whole day trying to figure out why firing click on parts of the select don't open the menu. Exporting `focus` would save a day for someone.

**Comment by romgain** [comment]
Hi @SpadarShut !

That's a good idea, thank you :)

Unfortunately I'm away without a computer for the next couple weeks, but I'd be happy to merge in a PR exporting the focus helper (and documenting it in the readme).
