### ISSUE TITLE
Unable to select option from the list in 4.1.3

### ISSUE THREAD

**Issue by G07cha** [romgain/react-select-event#19]
Seems like [new ignore rule](https://github.com/romgain/react-select-event/commit/ae7684bd741321ebc9334f6efc0cd7687658e93d#diff-f41e9d04a45c83f3b6f6e630f10117feR70) ignores regular options

https://codesandbox.io/s/kind-bohr-701mk

**Comment by romgain** [comment]
Hi @G07cha !

I downloaded the code from the codesandbox and ran the tests locally, but everything passes.

There might be something wrong with the way codesandbox runs the tests. 


Do you have other code samples that reproduce the issue?

Alternatively, could you PR a failing unit test that shows the problem?


Thanks!

**Comment by G07cha** [comment]
Hi @romgain,
Thanks for getting back to me so quickly, I've created a sample repository where I can reproduce the issue - https://github.com/G07cha/react-select-event-issue-repro
Hope that helps!

**Comment by romgain** [comment]
Thanks! I can repro the issue now. I'll try to publish a fix today 😃

**Comment by romgain** [comment]
Hi @G07cha !

This should now be fixed in v1.4.1 😃

Please reopen this if there are any other issues!

**Comment by G07cha** [comment]
Can confirm, the issue is fixed in v4.1.4, thanks a lot!

**Comment by romgain** [comment]
Great, thank you for checking! 😃
