### ISSUE TITLE
Add this to testing-library.com?

### ISSUE THREAD

**Issue by kentcdodds** [romgain/react-select-event#2]
Would you be interested in adding a reference to this library on the official website? I'm sure it'd help a lot of people!

It could be listed as one of the ecosystem projects.

![image](https://user-images.githubusercontent.com/1500684/58508412-39965b80-8151-11e9-9fe7-b642ac994baa.png)

Just create a ecosystem-react-select-event.md file here: https://github.com/testing-library/testing-library-docs/tree/master/docs then add that here: https://github.com/testing-library/testing-library-docs/blob/3582c10ad5f788b23cfeb2eaf8796a6cab3f819c/website/sidebars.json#L60-L65

Thanks for building this!

**Comment by romgain** [comment]
Of course, thanks for suggesting!
Let me know if I missed anything: https://github.com/testing-library/testing-library-docs/pull/121

And thank you so much for your work! :smile:
