### ISSUE TITLE
Feature request: Get list of options in select dropdown

### ISSUE THREAD

**Issue by fgs-dbudwin** [romgain/react-select-event#27]
There doesn't appear to be a way for `react-select-event` to return a list of the options in the select dropdown.  My use case is that I am trying to write a test to validate that an option appears in the select dropdown.

I think it would be a bit cleaner if I could instead do something like...

```js
const mySelectDropdown = screen.getByLabelText("My Select Dropdown");

// This assumes openMenu will return an array of options
const options = selectEvent.openMenu(mySelectDropdown);

await waitFor(() => {
    expect(options.filter(o => o.label === "Foo").length).toBe(1)
});
```

**Comment by romgain** [comment]
Hi @fgs-dbudwin !

I'm not sure that'd be possible, as we just have access to the DOM, not the actual option objects.


But you can directly check that the option is visible after opening the menu:

```js
const mySelectDropdown = screen.getByLabelText("My Select Dropdown");
selectEvent.openMenu(mySelectDropdown);

expect(getByText("Foo")).toBeInTheDocument();
```

See https://github.com/romgain/react-select-event/blob/master/src/__tests__/select-event.test.tsx#L49-L61 for another example.

**Comment by romgain** [comment]
Feel free to reopen if you have more questions!
