### ISSUE TITLE
Autofocus prop

### ISSUE THREAD

**Issue by Wgil** [romgain/react-select-event#29]
Hello,

I'm facing this issue https://github.com/JedWatson/react-select/issues/3655 when I try to use this library with `autoFocus` prop.

Any chance we can approach it?
Thanks

**Comment by romgain** [comment]
Hi @Wgil !

I tried adding the autoFocus prop, but the test suite still passes: https://github.com/romgain/react-select-event/commit/8c97e0deeaf982319383f06f26b1bbfb5c85ed31

Can you please send a PR with a failing test that shows the issue you're having?

Thanks!

**Comment by romgain** [comment]
Closing for now, but feel free to reopen if you can reproduce the issue
