### ISSUE TITLE
Option names are not showing when selectEvent.openMenu is used

### ISSUE THREAD

**Issue by ctoppel** [romgain/react-select-event#32]
I am not quite certain where the issue is, but when I use selectEvent.openMenu on the react-select component, the menu does indeed open and is seen in the debug in react-testing-library, but the actual human readable option names are not showing (see image and code below). 

<img width="335" alt="Screen Shot 2020-06-07 at 10 12 20 AM" src="https://user-images.githubusercontent.com/21048248/83975226-a5082280-a8a7-11ea-96f9-e8e7468ec2d4.png">

`<div
                        class=" css-1p2g4bj-menu"
                      >
                        <div
                          class=" css-4ljt47-MenuList"
                        >
                          <div
                            class=" css-w2llk3-option"
                            id="react-select-4-option-0"
                            tabindex="-1"
                          />
                          <div
                            class=" css-yt9ioa-option"
                            id="react-select-4-option-1"
                            tabindex="-1"
                          />
                          <div
                            class=" css-yt9ioa-option"
                            id="react-select-4-option-2"
                            tabindex="-1"
                          />
                        </div>
                      </div>`

**Comment by ctoppel** [comment]
Sorry, user error...

**Comment by ryanmagoon** [comment]
@ctoppel what ended up being your problem here? I'm having similar issues

**Comment by ctoppel** [comment]
Been a while, but think I ended up having to do a work around. I’ll look back at it and respond with some more info when I can.
