### ISSUE TITLE
Feature request: Create a new item without selecting it

### ISSUE THREAD

**Issue by fgs-dbudwin** [romgain/react-select-event#35]
**Problem:**

The `create` function in this library will automatically select the newly created value.  This is a reasonable idea, except when testing how your code handles things when the creation fails.  When I use this library's `create` function when testing my code I get the following error:

> TestingLibraryElementError: Unable to find an element with the text: NewOptionToCreate. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

This error is happening because in my unit test, the API fails to create the given option and this library is trying to select the option that wasn't created.

**Use case:**

In my code, when I create a new option it fires off a request to the backend API to create that text in the database.  There is no guarantee that this backend API will be available and working correctly, therefore, I expect to get a 4** or 5** HTTP error as the response from the API.  When this happens, my user interface will display a popup message to the user letting them know the creation failed.  When the creation fails, it's not possible to select it from the dropdown because it doesn't exist.

Looking at the `create` function in this library, I believe the `findByText` at the end is causing problems because it's assuming that the create will always succeed, and therefore that the new item will be in the dropdown.

```
export const create = async (
  input: HTMLElement,
  option: string,
  config: CreateConfig = {}
) => {
  const createOptionText = config.createOptionText || /^Create "/;
  openMenu(input);
  type(input, option);

  fireEvent.change(input, { target: { value: option } });
  await select(input, createOptionText, config);

  await findByText(getReactSelectContainerFromInput(input), option); <-- I believe this line should be optional
};
```

**Proposals:**

1. Add a new function like `createWithoutSelect`
2. Add a new parameter to the existing `create` like `autoSelect: boolean = true`

```
export const create = async (
  input: HTMLElement,
  option: string,
  config: CreateConfig = {},
  autoSelect: boolean = true
) => {
  const createOptionText = config.createOptionText || /^Create "/;
  openMenu(input);
  type(input, option);

  fireEvent.change(input, { target: { value: option } });
  await select(input, createOptionText, config);

  if (autoSelect) {
    await findByText(getReactSelectContainerFromInput(input), option);
  }
};
```

**Comment by romgain** [comment]
Hi @fgs-dbudwin !

Thanks for the suggestion!


I like option 2 - we should just make sure that the new option is added to the `config` object rather than as a new parameter.
I'd be happy to merge this if you could put together a quick PR!

Thanks!

**Comment by romgain** [comment]
Fixed in https://github.com/romgain/react-select-event/pull/36

**Comment by romgain** [comment]
@fgs-dbudwin v4.2.0 is now available on npm! Thanks again for your contribution!
