### ISSUE TITLE
Got TestingLibraryElementError when running tests

### ISSUE THREAD

**Issue by JLFullstack** [romgain/react-select-event#38]
Hi,

I am trying to test `react-select` with this library, and I was following documentation, I got ` TestingLibraryElementError: Found a label with the text of: Food, however no form control was found associated to that label. Make sure you're using the "for" attribute or "aria-labelledby" attribute correctly.`

Here is my code for the test, it is copied directly from documentation.
https://github.com/JLFullstack/react-select-testing/blob/master/src/openMenu.test.js

Here is the repository I set up to re-produce this issue.
https://github.com/JLFullstack/react-select-testing

**Comment by romgain** [comment]
Sorry for the confusion @JLFullstack !

That was an issue with the docs :disappointed: 

I updated the example here: https://github.com/romgain/react-select-event/commit/7e4b980288b1195d847966951c542278441a396c

Please, let me know if you have any other issues!

**Comment by JLFullstack** [comment]
@romgain Thanks for getting back to me.

Can you please take a look at this test as well?
https://github.com/JLFullstack/react-select-testing/blob/master/src/select.test.js

 I copied it from your example, and I got `Cannot read property 'body' of null`.

**Comment by romgain** [comment]
Hi @JLFullstack !

I just tried this, but the test passed :confused: 

Which version of react-testing-library and react-select-event are you using?

**Comment by JLFullstack** [comment]
Hi @romgain , this are my dependencies

```
    "@testing-library/jest-dom": "5.10.1",
    "@testing-library/react": "10.4.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-scripts": "3.4.1",
    "react-select": "3.1.0"
```

I am using "react-select-event": "5.0.0".

You can check out my repo to reproduce it. https://github.com/JLFullstack/react-select-testing

**Comment by romgain** [comment]
@JLFullstack 

Oh, I see. That's actually an issue with newer versions of @testing-library/react, not with react-select-event.
It's documented under the "MutationObserver shim removed" breaking change here: https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0

You can fix it by installing `jest-environment-jsdom-sixteen` and updating your test script:

```diff
  "scripts": {
    ...
-   "test": "react-scripts test --env=dom"
+   "test": "react-scripts test --env=jest-environment-jsdom-sixteen"
    ...
  },
```


Let me know if you have any other issues!
