### ISSUE TITLE
Helper for async selects?

### ISSUE THREAD

**Issue by Belco90** [romgain/react-select-event#4]
Helpers from this library are really useful for testing react-select together with RTL, but I'm missing a helper for [async component](https://react-select.com/async). Any plans about including this? Thanks.

**Comment by romgain** [comment]
Hi @Belco90 !

The helpers should also work with async inputs - see https://github.com/romgain/react-select-event/commit/dbc74307721457b7f8f2bcc3e13425147acba51d for instance.

Did you have a specific use case in mind?
It would be useful if you could share some code (or better a PR with a failing test case!)

**Comment by Belco90** [comment]
Ah didn't realize it's already working for async select! I didn't see anything on the doc so I just assume this wasn't implemented. I actually found an issue but I'm afraid it's related to RTL itself. Thanks for your help!

**Comment by romgain** [comment]
I added this to the docs - thanks for the feedback!

Feel free to reopen this if you think that the issue you saw could/should be fixed in `react-select-event`!

**Comment by Belco90** [comment]
I created a PR with some weird code when using helper for async creatable select. Let me know what you think!
