### ISSUE TITLE
TypeError: dom.waitFor is not a function

### ISSUE THREAD

**Issue by rohiniseetul** [romgain/react-select-event#42]
Thanks very much for this library. 

### Problem
When calling `clearFirst()` and `clearAll()` in tests, the following error is thrown:
_TypeError: dom.waitFor is not a function_

I can reproduce this in my own project and with a new CRA. I am using the following versions of these libraries:
`
"@testing-library/jest-dom": "4.2.4",
"@testing-library/react": "9.5.0",
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-scripts": "3.4.3",
"react-select": "3.1.0",
"react-select-event": "5.0.0"
`

Even using the latest version of the above libraries, produces the same issue.

It looks like the utility method `waitFor` is not available in the version of `@testing-library/dom` this library is using.

It would be much appreciated if you can take a look at the issue.

**Comment by romgain** [comment]
Good catch @rohiniseetul , thanks!

It should be fixed with #44

**Comment by rohiniseetul** [comment]
Many thanks. Is this fix available in the latest version of the library?
