### ISSUE TITLE
Examples without a form?

### ISSUE THREAD

**Issue by licx** [romgain/react-select-event#51]
It would be great to have some examples of how to use this library when react-select is used outside of a form

**Comment by wdfinch** [comment]
@romgain quick question. Why do you use `screen.getByRole("textbox")` as your query? When looking at react-select, I don't see a role of `textbok` rendered anywhere in dom. Why does this work? 

Additionally, it looks like you can't select by the label without a form. Is there anyway you could use a `data-test-id` to select when outside a form?

Thanks so much!

**Comment by romgain** [comment]
Hey @wdfinch !

`textbox` is the default role for input fields - see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles and https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role for more information.

In this case, we just need to target the input field within the react-select component. It doesn't really matter how, but the role selector can be a graceful solution 🙂

**Comment by wdfinch** [comment]
Ok, thanks so much for the help. I really appreciate it!

**Comment by wdfinch** [comment]
I think we could close this issue now.

**Comment by romgain** [comment]
Thanks @wdfinch ! Let me know if you have any other questions!
