### ISSUE TITLE
"MutationObserver is not a constructor" after upgrading to version 5.1

### ISSUE THREAD

**Issue by apieceofbart** [romgain/react-select-event#62]
I updated from "4.1.4" to "5.1.0" ale my tests fail with "MutationObserver is not a constructor" - I'm guessing that's because of the "@testing-library/dom@>=7" change (I am using jest 24.9)

**Comment by irfanalef2060** [comment]
I am facing the same issue

**Comment by romgain** [comment]
Apologies, it looks like 5.1.0 was a breaking change. 

I’m afraid your best bet for now is just to pin this library to version 5.0.0.

**Comment by romgain** [comment]
Unfortunately, I don’t think there’s much that can be done on this as the offending version is already published. 

I’ll close this for now, but feel free to reopen if you have suggestions!
