### ISSUE TITLE
Small typescript change

### ISSUE THREAD

**Issue by lpproulx** [romgain/react-select-event#68]
Hi,

Testing library allow to use a function as a [Text matcher](https://testing-library.com/docs/queries/about#textmatch) but it's not available in the types of react-select-event. Would it be possible to add this type for the select function?

I'm using the function matcher to fix [this problem](https://github.com/testing-library/dom-testing-library/issues/410#issuecomment-625873823) 

thank you for your work!

**Comment by romgain** [comment]
Hey @lpproulx ,

Thanks for the suggestion!
Would you be open to submitting a PR for this? If so, please make sure to add unit tests for all the new ways to select options :slightly_smiling_face:

**Comment by romgain** [comment]
fixed in #69
