### ISSUE TITLE
clearFirst not working

### ISSUE THREAD

**Issue by colinrcummings** [romgain/react-select-event#7]
Minimal reproduction [here](https://github.com/colinrcummings/react-select-event-issue-7/blob/ec9f3f0eead191f22f01a1d6532c16840cdf4d94/src/App.test.js#L12).

**Comment by romgain** [comment]
Thanks for reporting @colinrcummings !

This should now be fixed in version 2.1.2.

Let me know if you have any other issues!

**Comment by colinrcummings** [comment]
Thanks, @romgain. I'm still running into issues making a subsequent selection after clearing (updated the [repro](https://github.com/colinrcummings/react-select-event-issue-7/blob/master/src/App.test.js#L18)). 

It looks like the prior selection persists and the options may be gone (?):

```
// debug output
<span aria-live="polite" class="css-1laao21-a11yText">
  <p id="aria-selection-event">option Option 1, selected.</p>
  <p id="aria-context">
    0 results available. Select is focused , press Down to open the menu,
  </p>
</span>
```

I can see the options after clearing when I pass `<Select menuIsOpen />`:

```
// debug output
<span aria-live="polite" class="css-1laao21-a11yText">
  <p id="aria-selection-event">option Option 1, selected.</p>
  <p id="aria-context">
    option Option 1 focused, 1 of 3. 3 results available. Select is
    focused , press Down to open the menu,
  </p>
</span>
```

What's odd is that after passing `<Select menuIsOpen />` the subsequent selection works. Looking into it more; what do you think?

**Comment by romgain** [comment]
@colinrcummings It should be fixed in v3.0.0.
Let me know if that works for you.

Note that `clearFirst` and `clearAll` are both async now though - you'll need to update your test code.

**Comment by colinrcummings** [comment]
[Fixed](https://github.com/colinrcummings/react-select-event-issue-7/blob/f0e94365c5549f26e75feba40367c467f0196a36/src/App.test.js)! Thanks for your help with this @romgain.

**Comment by colinrcummings** [comment]
[Fixed](https://github.com/colinrcummings/react-select-event-issue-7/blob/f0e94365c5549f26e75feba40367c467f0196a36/src/App.test.js)! Thanks for your help with this @romgain.
