### ISSUE TITLE
Possible to add .scrollToBottom function?

### ISSUE THREAD

**Issue by DianaKoenraadt** [romgain/react-select-event#71]
I'm trying to trigger the `onMenuScrollToBottom` in a test. I haven't found a way to do this yet. It would be great if `selectEvent` would be extended with a .scrollToBottom function

**Comment by romgain** [comment]
Hey @DianaKoenraadt !

Unfortunately, I don’t think there’s a way to do this in this library- afaik, jsdom does not implement scrolling. 

Let me know if you find something that works though!

**Comment by DianaKoenraadt** [comment]
Thanks for your reply. I found some other topics mentioning this limitation of jsdom, yes. 
What I ended up doing was just calling the method that I had attached to 1onMenuScrollToBottom` directly from my test. Not exactly what I wanted, but at least I can test the rest of my component that way.

**Comment by romgain** [comment]
Glad you found a workaround 👍 

I’ll close this issue now, but feel free to reopen if you find something that we could do directly in the library
