### ISSUE TITLE
selectEvent.select not working after updating to react 18

### ISSUE THREAD

**Issue by sindrisig** [romgain/react-select-event#88]
after updating to react 18 the following test is failing

```
  it('testing selecting item', async () => {
    const onChangeSpy = jest.fn();
    const options = [
      {
        value: 1,
        label: 'One',
      },
      {
        value: 2,
        label: 'Two',
      },
    ];
    render(<Select options={options} value={undefined} label="Label" inputId="id" onChange={onChangeSpy} />);

    await selectEvent.select(screen.getByLabelText('Label'), ['Two']);

    expect(onChangeSpy).toHaveBeenCalledWith(options[1], expect.any(Object));
  });
```

The error message is 

```
Unable to find an element with the text: Two. This could 
be because the text is broken up by multiple elements. 
In this case, you can provide a function for 
your text matcher to make your matcher more flexible.
```

**Comment by romgain** [comment]
Thanks @sindrisig !

I don't think react-select currently supports react 18: https://github.com/JedWatson/react-select/issues/5129
Once react-select adds support for react 18 and if `react-select-event` doesn't work out of the box with the latest react and react-select, a PR to fix it here would be greatly appreciated! :-)

**Comment by sindrisig** [comment]
@romgain Thanks for the info. Will check this out again when react-select has been updated and like you said if it does not work out of the box i will try to fix it and create a PR

**Comment by romgain** [comment]
Awesome, thank you!

**Comment by rebelliard** [comment]
@morganr1 `openMenu(el)` worked for me. Thanks!

**Comment by annidai** [comment]
Is there a plan to fix this?

**Comment by romgain** [comment]
@annidai I unfortunately don’t have time to work on this right now, but I will merge PRs if anyone else can contribute a fix 😀

**Comment by reinertisa** [comment]
@sindrisig and @romgain I have the same problem. I commented all my react-select testing. Jenkins fails :( @sindrisig have you started to work on it? Thank you for your help.

**Comment by yechenchao** [comment]
@morganr1 it works for me too! Thanks!

**Comment by vcherevatyi-smartling** [comment]
It wasn't worked for me because menulist was into a react portal, onChange callback is called via
```jsx
fireEvent.mouseDown(screen.getByText("Tony"))
```

**Comment by npossamai** [comment]
> await selectEvent.openMenu

@morganr1 it worked for me too. Thank you!
