### ISSUE TITLE
Fails when `menuPortalTarget` is set to document.body

### ISSUE THREAD

**Issue by apieceofbart** [romgain/react-select-event#9]
If I am correct `react-select-event` is not able to test selects that are rendered with `menuPortalTarget` set to `document.body`. This prop is passed when you want to render select in modals and not have it hidden. 
I was trying to create a codesandbox to reproduce the behaviour but I am not even able to get the basic test to pass:
https://codesandbox.io/s/ancient-snowflake-4rs5l

**Comment by romgain** [comment]
Thanks for reporting @apieceofbart !

I just published v4.0.0 to npm, which should hopefully fix the issue.
You'll now need to specify a third parameter `{ container: document.body }` to your `select` and `create` calls if you're rendering the dropdown in a modal.

See the tests in https://github.com/romgain/react-select-event/commit/17ac6b3cc2f5f9b95eeed1dab647014bd8aa2ffa for more details.


Let me know if that fixes your issue!

**Comment by apieceofbart** [comment]
@romgain  Thanks a lot for quick resolution - tested it and it works fine!
